### ISSUE TITLE
Editing default CSS

### ISSUE THREAD

**Issue by abarth-ch** [Bonitasoft-Community/docker_bonita#30]
Hello,
I'm using Bonita BPM 7.9.4 with Kubernetes and I want to edit the default CSS.
I found the bonita-skin.css file in the pod which I edited but it looks like this file is generated everytime the pod is deleted.
The path is like this:
`/opt/bonita/BonitaCommunity-7.9.4-tomcat/server/temp/bonita_portal_1@POD_NAME/tenants/1/theme/portal/bonita-skin.css`

Do you have any recommendations or best practices for persisting change in bonita-skin.css in a safe way ?

Thank you in advance for your help.
Best regards,
Adrien

**Comment by tbouffard** [comment]
@abarth-ch 
Everything under `/opt/bonita/BonitaCommunity-7.9.4-tomcat/server/temp` is temporary: the files are retrieved at runtime from the Bonita configuration stored in the Bonita Database or directly from the Bonita Runtime (the bonita.war). That's why "it looks like this file is generated everytime the pod is deleted"

Bonita fully supports theming only with the Enterprise edition, https://documentation.bonitasoft.com/bonita/7.11/creating-a-new-look-feel, so in your case, you have to do hacky things.

With the Community edition, you can give a try to update the Docker image.
The css skin file should be located in the zip file `bonita-portal-theme-css.zip` in `WEB-INF/classes` of the bonita.war file stored in `/opt/bonita/BonitaCommunity-7.9.4-tomcat/server/webapps` in the image

cc @abirembaut

**Comment by abarth-ch** [comment]
Thank you for the explanation @tbouffard 
I'll try updating the Docker image!
Best regards.
