### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [Bonitasoft-Community/docker_bonita#6]
I was use this image to build on arm64 architecture and successed.So I think we can add it to https://hub.docker.com/u/arm64v8/ .  I use /7.5/Dockerfile to build and use FROM arm64v8/ubuntu:16.04

**Comment by tianon** [comment]
Since `bonita` is `FROM ubuntu:...` and simply installs `openjdk-8-jre-headless` and downloads some appropriate Java files, in theory it should support most (if not all) the same architectures that Ubuntu does (https://github.com/docker-library/official-images/blob/83445dba81738f34d37e13fa811b34841d1d6def/library/ubuntu#L40, `amd64, arm32v7, arm64v8, i386, ppc64le, s390x`).

See https://github.com/docker-library/official-images#architectures-other-than-amd64 and https://github.com/docker-library/official-images#multiple-architectures for more information about multi-architecture official images. :+1:

**Comment by philippelaumay** [comment]
Thanks a lot for your contribution and comments. 
It is always encouraging to see such involvement in our product. 
I understand the argument of Tianon but our support policy is strict and depend from many parameter not only related to the OS. It cannot be extended only from a single (very valuable) contribution. 

Unfortunately, there is no plan in the near future to support multiple architecture. It does not mean we won't but just that ARM architecture are not in our customer/community target for the moment. 
We'll follow that carefully and inform our community on this support when we'll be ready to integrate it. 

Best regards
Philippe 
Product Marketing Manager @ Bonitasoft

**Comment by lag-linaro** [comment]
@philippebonita, have you guys had any more thoughts about enabling ARM64v8?

We too have managed to build and run this project with no issues.

ARM64v8 is becoming very popular in the Enterprise of late - it would great if you could support it.

Please let me know if we can provide any support to expedite this process.

**Comment by odidev** [comment]
I managed to build and run ```Bonita``` successfully on ```arm64v8``` just by doing a minimum change of using ```gosu-1.10``` instead of ```gosu-1.6```

I would happy to raise a **PR** for this to include ```arm64v8```, if you guys agree for it.
I can also provide build and run logs as required for confirmation.

```Regarding demand for ARM```: Even, I agree that there is a huge demand for ARM-based architectures in the market. And it would be great if we start providing ```bonita``` for this.

**Comment by odidev** [comment]
In case, you are concerned regarding infrastructure to test ```arm64v8``` then,

Shippable supports free Arm64 CI/CD and I believe Codefresh does too (both 64-bit and 32-bit for both providers):

https://blog.shippable.com/shippable-arm-packet-deliver-native-ci-cd-for-arm-architecture
http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm/

CodeFresh Beta signup: https://goo.gl/forms/aDhlk56jZcblYokj1

If you need raw infrastructure the WorksOnArm project will supply full servers if you want to deal with metal: https://github.com/worksonarm/cluster/

**Comment by JeremJR** [comment]
Thanks all for your comments. As mentioned before, Bonita is not officially supported on ARM by Bonitasoft.
But thanks to all your inputs I'm trying to move forward on this point.
I've upgraded gosu to 1.10 as recomended by @odidev.
I've opened an issue on shippable regarding an issue to pull their image on an arm node https://github.com/Shippable/support/issues/4487
I'm waiting for an answer regarding the CodeFresh Beta.

**Comment by odidev** [comment]
That's great @JeremJR .
I hope to see ```Bonita``` running officially on ```arm64v8``` architecture very soon
 :smile: :crossed_fingers: 

Regards,

**Comment by JeremJR** [comment]
I've been able to build the image on both Shippable and CodeFresh. And I've run it on CodeFresh successfully.
I've opened this PR  https://github.com/docker-library/official-images/pull/4708 in order to add arm64v8 support

**Comment by odidev** [comment]
Thanks @JeremJR
It is really good to know that you made good use of both Shippable and CodeFresh.

Lets wait for official merge of PR now :) :)

**Comment by JeremJR** [comment]
Thank you @tianon to have merged this PR.
@longquan7, @lag-linaro, @odidev arm64v8 bonita images are available on Docker Hub.

**Comment by odidev** [comment]
Thank guys for quick support.
I guess ```Bonita``` image is still under processing for ```arm64v8``` as it is not fetching via ```docker pull bonita```

Maybe we need to wait for some more time :crossed_fingers:

**Comment by lag-linaro** [comment]
Build looks good:

https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/bonita

Image is also `docker pull`able.

Thanks guys.
